DROP DATABASE IF EXISTS burger_db;
CREATE DATABASE burger_db;

USE burger_db;

CREATE TABLE burgers (
  id INTEGER(11) NOT NULL AUTO_INCREMENT,
  burger_name VARCHAR(255) NULL,
  devoured INTEGER(11) NULL,
  PRIMARY KEY (id)
);